### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by adityachowta** [sourcey/s3-image-optimizer#11]
I have followed the steps mentioned in the Readme

I am stuck in this error 

Function Logs:
START RequestId: 90483eef-df2f-11e7-bbc7-6516e6da6e83 Version: $LATEST
2017-12-12T11:28:24.249Z	90483eef-df2f-11e7-bbc7-6516e6da6e83	Listing more keys: null
2017-12-12T11:28:24.382Z	90483eef-df2f-11e7-bbc7-6516e6da6e83	Processing 20170514105634280.png
2017-12-12T11:28:24.474Z	90483eef-df2f-11e7-bbc7-6516e6da6e83	in process
2017-12-12T11:28:24.494Z	90483eef-df2f-11e7-bbc7-6516e6da6e83	Error: spawn EACCES
    at exports._errnoException (util.js:870:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at exports.execFile (child_process.js:151:15)
    at ExecBuffer.<anonymous> (/var/task/node_modules/exec-buffer/index.js:91:3)
    at FSReqWrap.oncomplete (fs.js:82:15)

Any suggestions?

**Comment by grandadmiralmcb** [comment]
It looks like you don't have permission to run some files, Try by typing next command on the root path of your project:

chmod -R u+x .
If it is fixed now you must find which files had the incorrect permissions. Type next command if you want to undo changes to find those problematic files:

git checkout -- .
