### ISSUE TITLE
Error with validation

### ISSUE THREAD

**Issue by ChrisGrigg** [sourcey/s3-image-optimizer#3]
Hi I'm getting the following error in my CloudWatch logs:

START RequestId: d27a3501-3eac-11e6-bd3d-bd0a79092cb0 Version: $LATEST 
module initialization error: MissingRequiredParameter at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37) at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:61:14) at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:88:21) at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10) at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:89:42) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20) at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:95:12) at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:75:9 at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:307:7) at /var/runtime/node_modules/aws-sdk/lib/config.js:323:9 
END RequestId: d27a3501-3eac-11e6-bd3d-bd0a79092cb0

Any ideas?

**Comment by brian-kephart** [comment]
I am getting the same error.

**Comment by chrsgrffth** [comment]
You can get past this by adding `{ paramValidation: false }` to the s3 class, like so:

```
s3 = new aws.S3({ paramValidation: false })
```

This probably won't get things working completely, but it will at least help getting further along to figure out which params needs attention since the AWS error doesn't specify which parameter is missing.

**Comment by CraftLogan** [comment]
Same here. Fixed the first error message with @chrsgrffth suggestion but now I am getting "TypeError: handler is not a function"  Any idea's? Thanks

**Comment by Lunteer** [comment]
Has anyone gotten past this point? I also have the error "TypeError: handler is not a function".

I should note that to deploy I had to change the nodejs4.3 to nodejs8.10, not sure that has an effect.

**Comment by Lunteer** [comment]
The answer to this issue was right here in the issues. Check out [https://github.com/sourcey/s3-image-optimizer/issues/6](url). You need to edit the optimizer.js file.

I am up to the issue of getting the bucket name correct :)
